json.extract! business, 
              :id, 
              :name, 
              :category, 
              :address, 
              :city, 
              :state, 
              :zip_code,
              :phone_number,
              :website_url,
              :owner_id